<a href="https://colab.research.google.com/github/Aldistwn29/Nupy_2/blob/main/Numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## lanjutan

In [3]:
import numpy as np

# Slicing and Indexing

Fild Access dan Basic Indexing

In [ ]:
# contoh 1 index tunggal, field index
a = np.arange(10)
print(a)
b = a[5]
print(b)

[0 1 2 3 4 5 6 7 8 9]
5


In [ ]:
# contoh 2
a = np.arange(10)
print(a)
s = slice(2,7,2)
print(a[s])

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [ ]:
# Contoh 3
a = np.arange(10)
b = a[2:7:2]
print(b)

[2 4 6]


# Slicing

In [ ]:
# contoh 4 slicing index hanya dengan menggunakan prameter start
a = np.arange(10)
print(a)
print(a[2:])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]


In [ ]:
# contoh 5 slicing menggunakan start dan stop index
a = np.arange(10)
print(a)
print(a[2:5])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]


In [ ]:
# contoh 6 slicing pada array 2 dimensu
a = np.array([[2,4,5], [3,4,5], [9,4,3]])
print(a)

# slicing itemn starting from index
print("Slicing index Array dari a[1:]")
print(a[1:])

[[2 4 5]
 [3 4 5]
 [9 4 3]]
Slicing index Array dari a[1:]
[[3 4 5]
 [9 4 3]]


In [ ]:
# contoh 7 mengggunakan ellipsis (...)
a = np.array([[2,4,5],
               [3,5,3],
               [5,6,7]])
print('Array kita:')
print(a)
print('\n')

# ini mengambilkan item di kolom kedua dari array utam
print('item dari kolom kedua:')
print(a[...,1])
print('\n')

# slicing semua item dari baris kedua
print('Item dari baris kedua:')
print(a[1,...])
print('\n')

# mengambil item dari kolom 1 dan seterusnya
print('Item dari kolom 1 dan setrusnya:')
print(a[...,1:])
print('\n')

Array kita:
[[2 4 5]
 [3 5 3]
 [5 6 7]]


item dari kolom kedua:
[4 5 6]


Item dari baris kedua:
[3 5 3]


Item dari kolom 1 dan setrusnya:
[[4 5]
 [5 3]
 [6 7]]




In [ ]:
# Study case
# 1. Buat array 2 dimensi dengan shape(3,4)
# 2. index dengan mengambil item baris kedua dan seterusnya sampai bariss terakhir
# 3. index dengan mengambil item dari kolom 1 dan 2
print('1')
a = np.arange(12)
print(a)

1
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
b = np.reshape(a, newshape=(3, 4), order='C')
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
print('3')
print(b[...,1:3])

3
[[ 1  2]
 [ 5  6]
 [ 9 10]]


# Adavance Indexing

# Integer Index

In [ ]:
# contoh 1: mengambil elements dari array 2 Dimensi dengan menentukan baris dan kolom yg di salin
x = np.array([[1, 3],
              [2, 4],
              [3, 2]])
y = x[[0,1,2], [0,1,1]]
print(y)

[1 4 2]


In [ ]:
# contoh 2 mengakses elements index dari array
# 2 Dimensi dengan menentukan baris dan kolom yg di salin
x = np.array([[1, 3, 5, 2],
              [2, 4, 2, 1],
              [3, 2, 1, 4],
              [2, 3, 1, 2]])
print('Array Asli:')
print(x)

cols = np.array([[0,0], [2,2]]) #baris ke 1 dan 2
rows = np.array([[0,2], [0,3]]) # colum ke 2 dan 3
y = x[cols,rows]
print('Hasil dari index integer:')
print(y)

Array Asli:
[[1 3 5 2]
 [2 4 2 1]
 [3 2 1 4]
 [2 3 1 2]]
Hasil dari index integer:
[[1 5]
 [3 4]]


In [ ]:
# contoh 3
x = np.array([[1, 0, 3],
              [6, 8, 5],
              [3, 2, 1],
              [3, 2, 4]])
print('Array Asli:')
print(x)
print('\n')
# slicing
s = x[1:4,1:3]

print('Setelah, hasil array menjadi:')
print(s)
print('\n')

# using advance index for column
y = x[1:4,[1,2]]
a = x[1:4,[0,1,2]]
print('Slicing dengan advance index untuk columns')
print(y)
print(a)

Array Asli:
[[1 0 3]
 [6 8 5]
 [3 2 1]
 [3 2 4]]


Setelah, hasil array menjadi:
[[8 5]
 [2 1]
 [2 4]]


Slicing dengan advance index untuk columns
[[8 5]
 [2 1]
 [2 4]]
[[6 8 5]
 [3 2 1]
 [3 2 4]]


# Boolean indexing

In [ ]:
# contoh mengambil elemen dengan index boolean(kondisi)
x = np.array([[12, 1, 2, 4],
              [3, 4, 3, 5],
              [6, 7, 8, 12],
              [11, 9, 7, 0]])
print('Array asli:')
print(x)
print('\n')

# How we will print the items greater than 5
print('item yg lebih besar dari 5:')
print(x[x > 5])

Array asli:
[[12  1  2  4]
 [ 3  4  3  5]
 [ 6  7  8 12]
 [11  9  7  0]]


item yg lebih besar dari 5:
[12  6  7  8 12 11  9  7]


In [ ]:
# contoh 2
a = np.array((np.nan,1,2,np.nan,3,4,5))
print(a[np.isnan(a)])
# yg bukan nan
print(a[~np.isnan(a)])

[nan nan]
[1. 2. 3. 4. 5.]


In [ ]:
# contoh 3
a = np.array([1,3,2+6j,3.5+4j])
# print(a[~np.iscomplex(a)])
print(a)

[1. +0.j 3. +0.j 2. +6.j 3.5+4.j]


Study Case:
1. Buat Array 2 dimensi dengan shape(3,4) yg isinya campuran antara integer,complex, dan nan
2.Ambil item dengan index boolean khusus untuk integer, nan dan complex  

In [ ]:
# isi dari pertanyaan di atas
print('jwb no 1')
a = np.array([[1, 3.9+2j, np.nan, 4],
              [2+6j, 6, np.nan, 5],
              [np.nan, 7+1j, 2, np.nan]])

print(a)

print('jwb no 2')
# print((a[(~np.isnan(a)) & (~np.iscomplex(a)) & (a > 2)]))
print('integer')
print(a[(~np.iscomplex(a)) & (~np.isnan(a))])
print('nan')
print(a[np.isnan(a)])
print('complex')
print(a[np.iscomplex(a)])

jwb no 1
[[1. +0.j 3.9+2.j nan+0.j 4. +0.j]
 [2. +6.j 6. +0.j nan+0.j 5. +0.j]
 [nan+0.j 7. +1.j 2. +0.j nan+0.j]]
jwb no 2
integer
[1.+0.j 4.+0.j 6.+0.j 5.+0.j 2.+0.j]
nan
[nan+0.j nan+0.j nan+0.j nan+0.j]
complex
[3.9+2.j 2. +6.j 7. +1.j]


# Mengubah Shape

# reshape

In [13]:
a = np.arange(8)
print('Array asli:')
print(a)
print('\n')


b = a.reshape(4,2)
print('Array yg telah di modifikasi')
print(b)

Array asli:
[0 1 2 3 4 5 6 7]


Array yg telah di modifikasi
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


# Flatten

In [18]:
a = np.arange(8).reshape(2,4)

print('Array asli:')
print(a)
print('\n')

print('Array yg telah di modifikasi:')
print(a.flatten())
print('\n')

print('Flattened array dalam F-style ordering:')
print(a.flatten(order = 'F'))

Array asli:
[[0 1 2 3]
 [4 5 6 7]]


Array yg telah di modifikasi:
[0 1 2 3 4 5 6 7]


Flattened array dalam F-style ordering:
[0 4 1 5 2 6 3 7]


# Ravel

In [26]:
a = np.arange(8).reshape(2,4)

print('Array asli:')
print(a)
print('\n')

print('hasil dari fungsi ravel:')
print(a.ravel())
print('\n')

print('menggunakan ravel function dalam F-stayle ordering:')
print(a.ravel(order = 'F'))

Array asli:
[[0 1 2 3]
 [4 5 6 7]]


hasil dari fungsi ravel:
[0 1 2 3 4 5 6 7]


menggunakan ravel function dalam F-stayle ordering:
[0 4 1 5 2 6 3 7]


# Transpose

In [35]:
a = np.arange(12).reshape(4,3)

print('Array asli:')
print(a)
print('\n')

print('Array yang telah di modifikasi:')
print(np.transpose(a))
print('\n')

print('Array yg telah di transpose:')
print(a.T)

Array asli:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


Array yang telah di modifikasi:
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


Array yg telah di transpose:
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


# Conncate

In [56]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])

print('Array Asli:')
print(a)
print('\n')

print('Array Kedua:')
print(b)
print('\n')
# both the arrays are of same dimension

print('Gabungan dua array di sumbu:0')
print(np.concatenate((a,b)))
print('\n')

print('Gabungan dua array di sumbu:1')
print(np.concatenate((a,b), axis=1))
print('\n')

Array Asli:
[[1 2]
 [3 4]]


Array Kedua:
[[5 6]
 [7 8]]


Gabungan dua array di sumbu:0
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Gabungan dua array di sumbu:1
[[1 2 5 6]
 [3 4 7 8]]




# stack

In [62]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],
              [7,8]])

print('Array Asli:')
print(a)
print('\n')

print('Array kedua:')
print(b)
print('\n')

print('Stack dua array pada sumbu=0')
print(np.stack((a,b),0))
print('\n')

print('Stack dua array pada sumbu=1')
print(np.stack((a,b),1))
print('\n')

Array Asli:
[[1 2]
 [3 4]]


Array kedua:
[[5 6]
 [7 8]]


Stack dua array pada sumbu=0
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Stack dua array pada sumbu=1
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]




In [68]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print('Array Asli:')
print(a)
print('\n')

print('Array kedua:')
print(b)
print('\n')

print('Horizontal stacking:')
c = np.hstack((a,b))
print(c)
print('\n')

Array Asli:
[[1 2]
 [3 4]]


Array kedua:
[[5 6]
 [7 8]]


Horizontal stacking:
[[1 2 5 6]
 [3 4 7 8]]




# vstack

In [74]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print('Array Asli:')
print(a)
print('\n')

print('Array kedua:')
print(b)
print('\n')

print('Vertikal stacking:')
c = np.vstack((a,b))
print(c)

Array Asli:
[[1 2]
 [3 4]]


Array kedua:
[[5 6]
 [7 8]]


Vertikal stacking:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Splitting Array

# split

In [98]:
a = np.arange(9)

print('Array pertama:')
print(a)
print('\n')

print('split array menjadi 3 sub-array yg setara:')
b = np.split(a,3)
print(b)
print('\n')

print('split berdasarkan index pada array 1 dimensi:')
b = np.split(a,[4,5]) # numpy.split(ary, indices_or_section, axis)
# parameter indices_or_section dapat berupa bilangan bulat
print(b)

Array pertama:
[0 1 2 3 4 5 6 7 8]


split array menjadi 3 sub-array yg setara:
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


split berdasarkan index pada array 1 dimensi:
[array([0, 1, 2, 3]), array([4]), array([5, 6, 7, 8])]


# hsplit

In [114]:
a = np.arange(16).reshape(4,4)

print('Array pertama:')
print(a)
print('\n')

print('Horizontal spliting:') # columns wise
b = np.hsplit(a,2)
print(b)

Array pertama:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Horizontal spliting:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


# vsplit

In [116]:
a = np.arange(16).reshape(4,4)

print('Array pertama:')
print(a)
print('\n')

print('Vertical splitting:')
b =  np.vsplit(a,2)
print(b)

Array pertama:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Vertical splitting:
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


# Mengubah Element Array(Add/Remove)

# Resize


In [126]:
# Risize
a = np.array([[1,2,3],
              [4,5,6]])

print('Array Awal:')
print(a)
print('\n')

print('shape array pertama:')
print(a.shape)
print('\n')
b = np.resize(a,(3,2))

print('Array pertama:')
print(b)
print('\n')

print('shape array kedua:')
print(b.shape)
print('\n')

# Observe that frist row of a is repeated in b since size is bigger

print('resize array kedua:')
b = np.resize(a,(4,3))
print(b)

Array Awal:
[[1 2 3]
 [4 5 6]]


shape array pertama:
(2, 3)


Array pertama:
[[1 2]
 [3 4]
 [5 6]]


shape array kedua:
(3, 2)


resize array kedua:
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


# Append

In [137]:
# Append
print('Array Awal:')
print(a)
print('\n')

print('Append elements to array:')
print(np.append(a,[7,8,9]))
print('\n')

print('Append elements along axis:0')
print(np.append(a,[[7,8,9]], axis=0))
print('\n')

print('Append elements along axis:1')
print(np.append(a,[[7,8,9],[7,7,7]], axis=1))

Array Awal:
[[1 2 3]
 [4 5 6]]


Append elements to array:
[1 2 3 4 5 6 7 8 9]


Append elements along axis:0
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Append elements along axis:1
[[1 2 3 7 8 9]
 [4 5 6 7 7 7]]


# Insert

In [144]:
# insert
a = np.array([[1,2],
              [3,4],
              [5,6]])
print('Array Awal:')
print(a)
print('\n')

print('tanpa parameter axis. sebelum insertion arraynya di flattened.')
print(np.insert(a,3,[11,12]))
print('\n')
print('Menggunakan parameter axis. value arraynya di broadcasr untuk menyamakan input.')

print('Brodcast sepanjang axis = 0')
print(np.insert(a,1,[11],axis=0))
print('\n')

print('Broadcast sepanjang axis=1:')
print(np.insert(a,1,11,axis=1))

Array Awal:
[[1 2]
 [3 4]
 [5 6]]


tanpa parameter axis. sebelum insertion arraynya di flattened.
[ 1  2  3 11 12  4  5  6]


Menggunakan parameter axis. value arraynya di broadcasr untuk menyamakan input.
Brodcast sepanjang axis = 0
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


Broadcast sepanjang axis=1:
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


# delete

In [147]:
# delete
a = np.arange(12).reshape(3,4)
print('Frist Array')
print(a)
print('\n')

print('tanpa parameter axis maka di flattend sebelum di delete')
print(np.delete(a,5))
print('\n')

print('kolom 2 deleted')
print(np.delete(a,1,axis=1))

Frist Array
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


tanpa parameter axis maka di flattend sebelum di delete
[ 0  1  2  3  4  6  7  8  9 10 11]


kolom 2 deleted
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


# Unique elements

In [153]:
a = np.array([5,2,6,2,7,5,8,2,9])
print("Frist Array")
print(a)
print('\n')

print('value unik dari array pertama')
u = np.unique(a)
print(u)
print('\n')

print('index array:')
u, indices = np.unique(a, return_index = True)
print(indices)
print('\n')

Frist Array
[5 2 6 2 7 5 8 2 9]


value unik dari array pertama
[2 5 6 7 8 9]


index array:
[1 0 2 4 6 8]


