In [2]:
import numpy as np

Slicing and Indexing

Fild Access dan Basic Indexing

In [5]:
# contoh 1 index tunggal, field index
a = np.arange(10)
print(a)
b = a[5]
print(b)

[0 1 2 3 4 5 6 7 8 9]
5


In [9]:
# contoh 2
a = np.arange(10)
print(a)
s = slice(2,7,2)
print(a[s])

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [11]:
# Contoh 3
a = np.arange(10)
b = a[2:7:2]
print(b)


[2 4 6]


In [15]:
# contoh 4 slicing index hanya dengan menggunakan prameter start
a = np.arange(10)
print(a)
print(a[2:])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]


In [16]:
# contoh 5 slicing menggunakan start dan stop index
a = np.arange(10)
print(a)
print(a[2:5])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]


In [32]:
# contoh 6 slicing pada array 2 dimensu
a = np.array([[2,4,5], [3,4,5], [9,4,3]])
print(a) 

# slicing itemn starting from index
print("Slicing index Array dari a[1:]")
print(a[1:])

[[2 4 5]
 [3 4 5]
 [9 4 3]]
Slicing index Array dari a[1:]
[[3 4 5]
 [9 4 3]]


In [40]:
# contoh 7 mengggunakan ellipsis (...)
a = np.array([[2,4,5],
               [3,5,3],
               [5,6,7]])
print('Array kita:')
print(a)
print('\n')

# ini mengambilkan item di kolom kedua dari array utam
print('item dari kolom kedua:')
print(a[...,1])
print('\n')

# slicing semua item dari baris kedua
print('Item dari baris kedua:')
print(a[1,...])
print('\n')

# mengambil item dari kolom 1 dan seterusnya
print('Item dari kolom 1 dan setrusnya:')
print(a[...,1:])
print('\n')


Array kita:
[[2 4 5]
 [3 5 3]
 [5 6 7]]


item dari kolom kedua:
[4 5 6]


Item dari baris kedua:
[3 5 3]


Item dari kolom 1 dan setrusnya:
[[4 5]
 [5 3]
 [6 7]]




In [31]:
# Study case
# 1. Buat array 2 dimensi dengan shape(3,4)
# 2. index dengan mengambil item baris kedua dan seterusnya sampai bariss terakhir
# 3. index dengan mengambil item dari kolom 1 dan 2
print('1')
a = np.arange(12)
print(a)


1
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [33]:
b = np.reshape(a, newshape=(3, 4), order='C')
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [47]:
print('3')
print(b[...,1:3])

3
[[ 1  2]
 [ 5  6]
 [ 9 10]]
